services:
  - type: web
    name: shipsy-inventory-manager
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_PATH
        value: ./backend/src